CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE extras
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    price INTEGER                                 NOT NULL,
    CONSTRAINT pk_extras PRIMARY KEY (id)
);

CREATE TABLE food_extras
(
    extra_id BIGINT NOT NULL,
    food_id  BIGINT NOT NULL
);

CREATE TABLE foods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       INTEGER                                 NOT NULL,
    category_id BIGINT,
    CONSTRAINT pk_foods PRIMARY KEY (id)
);

CREATE TABLE order_item_extras
(
    extra_id      BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL
);

CREATE TABLE order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT,
    food_id  BIGINT,
    quantity INTEGER                                 NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    status      VARCHAR(255),
    total_price INTEGER                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE permission
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_permission PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL
);

ALTER TABLE foods
    ADD CONSTRAINT FK_FOODS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_FOOD FOREIGN KEY (food_id) REFERENCES foods (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE food_extras
    ADD CONSTRAINT fk_fooext_on_extra FOREIGN KEY (extra_id) REFERENCES extras (id);

ALTER TABLE food_extras
    ADD CONSTRAINT fk_fooext_on_food FOREIGN KEY (food_id) REFERENCES foods (id);

ALTER TABLE order_item_extras
    ADD CONSTRAINT fk_orditeext_on_extra FOREIGN KEY (extra_id) REFERENCES extras (id);

ALTER TABLE order_item_extras
    ADD CONSTRAINT fk_orditeext_on_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_permission FOREIGN KEY (roles_id) REFERENCES permission (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);